// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcmbHCCimP00hoqFArSowYC_lcqzdJIv0',
    appId: '1:802896587516:web:df47ed8289eaf7b39ec579',
    messagingSenderId: '802896587516',
    projectId: 'sumberku',
    authDomain: 'sumberku.firebaseapp.com',
    storageBucket: 'sumberku.firebasestorage.app',
    measurementId: 'G-7DTBZW16WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_n6kywKCBo9PxbYkmcjkPtm-eVH-5vmo',
    appId: '1:802896587516:android:8838984e4587c2f99ec579',
    messagingSenderId: '802896587516',
    projectId: 'sumberku',
    storageBucket: 'sumberku.firebasestorage.app',
  );
}
